######################
# Universal properties
######################

# "ignored" property...
# Determines which resources bypass the security filter chain altogether.
# This is important for more than efficiency as, without it, you might find
# the security system trying to redirect to one of these resources after a
# login, which won't work in a variety of odd ways.
# So, whenever you add a folder to /src/main/resources/public, you'll probably
# want to add it here, too.  

security:
    ignored: /css/**,/js/**,/img/**,/fonts/**,/plugins/**,/**/favicon.ico

spring:
    thymeleaf:
        cache: true
        prefix: templates/
    jpa:
        show-sql: false
    datasource:
        platform: mysql
        driverClassName: com.mysql.jdbc.Driver
        initialize: false
        test-on-borrow: true
        validation-query: do 1
        test-while-idle: false
        time-between-eviction-runs-millis: 30000
        min-evictable-idle-time-millis: 30000
        max-wait-millis: 10000

email:
    host: localhost
    port: 25
    defaultSender: no-reply@predictweasel.org

webapp:
    hostname: predictweasel.org
    protocol: http

# PredictWeasel properties

predictWeasel:
    passwordResetExpiryIntervalDays: 1
    minimumNumberOfFixturesToDisplay: 5
    maximumNumberOfStandingsToDisplay: 5
    elapsedTimeClockStartTime:
    adminEmailAddress: andrew@braycastle.co.uk            
    allowAutoSubscription: true
    
---

spring:
    profiles: live
    
    datasource:
        url: jdbc:mysql://localhost/pwlive
        username: pwliveuser
        password: pwlive

server:
    port: 80
                        
---

spring:
    profiles: test
    
    datasource:
        url: jdbc:mysql://localhost/pwtest
        username: pwtestuser
        password: pwtest

server:
    port: 80

predictWeasel:
    elapsedTimeClockStartTime: !!str 2014-06-13T16:00:00+01:00                                
---

spring:
    profiles: dev

    thymeleaf:
        cache: false
    datasource:
        url: jdbc:mysql://localhost/pw
        username: pwuser
        password: pwuser
        initialize: true
        
email:
    port: 12345

webapp:
    hostname: localhost:8080

predictWeasel:
    elapsedTimeClockStartTime: !!str 2014-05-02T12:00:00+01:00        